fpath=(~/.zsh/functions $fpath)
autoload -U ~/.zsh/functions/*(:t)

. ~/.zsh/environment
. ~/.zsh/aliases
. ~/.zsh/completion

if [[ -f ~/.zsh/local ]] ; then source ~/.zsh/local ; fi
source ~/.zsh/docker

HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.history
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt no_global_rcs

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
if which nodenv > /dev/null; then eval "$(nodenv init -)"; fi

export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"
